name: Go

on:
  push:
    branches: [ main ]
    paths: 
      - 'golang/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'golang/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      working-directory: ./golang
      run: go build -v ./...

    - name: Test
      working-directory: ./golang
      run: go test -v ./...
