name: Rust

on:
  push:
    branches: [ main ]
    paths: 
      - 'rust/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'rust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
  
     runs-on: ubuntu-latest
     
     steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            override: true
            components: rustfmt
      - name: Format check
        working-directory: ./rust
        run: cargo fmt -- --check
  
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./rust
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./rust
      run: cargo test --verbose
